# Generated by Django 3.2.8 on 2021-11-10 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faq.faq_answer'),
        ),
    ]
