# Generated by Django 3.2.8 on 2021-11-11 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211109_1737'),
        ('faq', '0002_auto_20211110_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_answer',
            name='answerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
    ]
