# Generated by Django 3.2.8 on 2021-11-11 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20211111_1332'),
        ('faq', '0003_alter_faq_answer_answerer'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_answer',
            name='answer_content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='content.contents'),
            preserve_default=False,
        ),
    ]
