# Generated by Django 3.2.8 on 2021-11-11 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_faq_answer_answer_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq_answer',
            name='answer_content',
        ),
    ]
