# Generated by Django 3.2.8 on 2021-11-15 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_remove_faq_answer_answer_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='faq.faq'),
        ),
    ]
