# Generated by Django 3.2.8 on 2021-10-29 02:56

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211029_1155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
