# Generated by Django 3.2.8 on 2021-10-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='baby_birth',
            field=models.DateField(null=True),
        ),
    ]
