# Generated by Django 3.2.8 on 2021-11-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_baby_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='bank_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/bankImage'),
        ),
        migrations.AlterField(
            model_name='host',
            name='crimelog',
            field=models.ImageField(blank=True, null=True, upload_to='images/crimeLogImage'),
        ),
    ]
