# Generated by Django 3.2.8 on 2021-11-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_host_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='id_card',
        ),
        migrations.AddField(
            model_name='host',
            name='id_card1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='id_card2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
