# Generated by Django 3.2.8 on 2021-11-09 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20211109_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='crimelog',
            field=models.ImageField(blank=True, null=True, upload_to='ßimages/crimeLogImage'),
        ),
        migrations.AlterField(
            model_name='host',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
