# Generated by Django 3.2.8 on 2021-10-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents_detail',
            name='detail_number',
            field=models.IntegerField(null=True),
        ),
    ]
