# Generated by Django 3.2.8 on 2021-11-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211109_1737'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
        migrations.AddField(
            model_name='contents_detail',
            name='host_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
    ]
