# Generated by Django 3.2.8 on 2021-11-11 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_auto_20211111_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='payed_user',
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserve_alive', models.BooleanField(default=True)),
                ('canceled_at', models.DateTimeField(null=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.contents')),
                ('reserve_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
